// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVGuFa8YoXEmUKBZcdMrk_vz3booW1Qg',
    appId: '1:867416985178:web:533facf8361bead7c9d263',
    messagingSenderId: '867416985178',
    projectId: 'perfectrenting-d1461',
    authDomain: 'perfectrenting-d1461.firebaseapp.com',
    storageBucket: 'perfectrenting-d1461.appspot.com',
    measurementId: 'G-DW8K8PZ96D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWJk38sLVO2S4PFAaDl16YZs6CarzDGQ',
    appId: '1:867416985178:android:fdb9654c6f74b002c9d263',
    messagingSenderId: '867416985178',
    projectId: 'perfectrenting-d1461',
    storageBucket: 'perfectrenting-d1461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsHRuCTMYQ0ZDO38USfNuU9NTQjCz4dyI',
    appId: '1:867416985178:ios:19dde8621cc840aac9d263',
    messagingSenderId: '867416985178',
    projectId: 'perfectrenting-d1461',
    storageBucket: 'perfectrenting-d1461.appspot.com',
    iosClientId: '867416985178-mdmbk8lfas1rh0mrqskn4cqtmtepguq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectRenting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsHRuCTMYQ0ZDO38USfNuU9NTQjCz4dyI',
    appId: '1:867416985178:ios:19dde8621cc840aac9d263',
    messagingSenderId: '867416985178',
    projectId: 'perfectrenting-d1461',
    storageBucket: 'perfectrenting-d1461.appspot.com',
    iosClientId: '867416985178-mdmbk8lfas1rh0mrqskn4cqtmtepguq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectRenting',
  );
}
